### ISSUE TITLE
[Feature request] Add a parameter to sort by real folder/file names when using `sortMenusOrderNumerically` and `useFolderTitleFromIndexFile` or `useTitleFromFileHeading`

### ISSUE THREAD

**Issue by joris-fonck-loreal** [jooy2/vitepress-sidebar#136]
Hello,

First, thank you for your amazing vitepress plugin!

I was studying the features and I have a use case that doesn't seem to be implemented.

# Feature

When using `sortMenusOrderNumerically` and `useFolderTitleFromIndexFile` together, the sorting rely on the title of the `index.md`.

I would like to sort them by the real folder name, which are named when the convention (e.g `['1-a', '2-a', '10-a']`).

Is it something possible?

Regards.

**Comment by jooy2** [comment]
Hello, thank you for using `vitepress-sidebar`.

The feature you requested was added in version 1.20.0 with the `sortMenusOrderNumericallyFromLink` option.
(The previous option, `sortMenusOrderNumerically`, has been changed to `sortMenusOrderNumericallyFromTitle`.)
Please refer to the `README.md` file for more information.

Thank you for your feature request and please open a new issue if you encounter any further issues.

Regards,
