### ISSUE TITLE
`useFolderLinkFromIndexFile` generate relative path and cause nesting of routing errors

### ISSUE THREAD

**Issue by baka-gourd** [jooy2/vitepress-sidebar#142]
https://github.com/jooy2/vitepress-sidebar/blob/bccbe7617b29cf8bfbe3b7629e74189702921b0f/lib/index.ts#L370

When use `useFolderLinkFromIndexFile`, there will generate a relative path and cause nesting of routing errors

In my case, I'm manually adding / to the front via a post-processing function.

**Comment by jooy2** [comment]
Hello, thank you for using `vitepress-sidebar`.

I recently fixed an issue with version 1.20.0 where folder links with some indexes were not being created correctly.
Could you please check if the issue occurs after upgrading to that version?

If the issue persists, please leave a comment with more details of the issue and i'll take a look.

Regards,

**Comment by baka-gourd** [comment]
Yeah, problem solved.
