### ISSUE TITLE
Enhance the navigation bar to exclude markdown files marked as 'draft,' ensuring only finalized content is displayed.

### ISSUE THREAD

**Issue by JurreBrandsenInfoSupport** [jooy2/vitepress-sidebar#149]
Introduce a new functionality with a flag named `excludeDraftFiles` to parse the frontmatter of markdown files. When encountering a file with the `draft: true` parameter, it will be omitted from the sidebar, ensuring that only completed content is included in the navigation.

**Comment by jooy2** [comment]
Hello, thank you for using `vitepress-sidebar`.

This can be fixed in version `1.23.0` by setting the `excludeFilesByFrontmatterFieldName` option value to `draft`.

If you encounter any other issues, please create a new issue.

Regards,
