### ISSUE TITLE
Using the sidebar exported by this plugin, the Prev Next Links of this page cannot be automatically generated?

### ISSUE THREAD

**Issue by UFO-001** [jooy2/vitepress-sidebar#156]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. Chrome, Safari]

**Additional context** Add any other context about the problem here.

**Comment by jooy2** [comment]
Hello, thank you for using `vitepress-sidebar`.

Please fill in the issue details about what issue you are experiencing and how to reproduce it. The issue title alone will not help us to resolve the issue.

Generally speaking, automatically created links support creating prev/next links. If you are not seeing prev/next links, it is possible that you have a different directory structure or the URLs are being handled incorrectly.

**Comment by jooy2** [comment]
Not responding to the answer, please open a new issue with a detailed description if the issue is still reproduced.
