### ISSUE TITLE
broken documentation links

### ISSUE THREAD

**Issue by clabnet** [jooy2/vitepress-sidebar#160]
In readme on github page there are broken documentation links : 

https://vitepress-sidebar.jooy2.com/getting-started

**Comment by jooy2** [comment]
Hello! Thank you for using `vitepress-sidebar` plugin!

I recently reworked the documentation page structure. The `getting-started` link has been changed to:
https://vitepress-sidebar.jooy2.com/guide/getting-started

Regards,

**Comment by jooy2** [comment]
Oops, The `README.md` was missing this link, i'll fix it.
Thank you for reporting this!
