### ISSUE TITLE
[RESOLVED] URL does not include resolvePath

### ISSUE THREAD

**Issue by DanielTrommel** [jooy2/vitepress-sidebar#164]
**Describe the bug** A clear and concise description of what the bug is.

The path is not updated with `resolvePath`, when using `scanStartPath`.
(at least, this is what I expected to see based on the examples)

**To Reproduce** Steps to reproduce the behavior:

1. Clone this repo

2. Replace the "Single sidebar example" (in this repository) with this:

```
    // Single sidebar example
    sidebar: generateSidebar([
      {
        debugPrint: true,
        documentRootPath: 'docs',
        scanStartPath: 'guide',
        resolvePath: '/guide/',
        manualSortFileNameByPriority: ['guide', 'advanced-usage'],
        excludeFiles: ['changelog.md'],
        collapsed: false,
        capitalizeFirst: true,
        useTitleFromFileHeading: true,
        useTitleFromFrontmatter: true,
        frontmatterOrderDefaultValue: 9, // For 'CHANGELOG.md'
        sortMenusByFrontmatterOrder: true
      },
      {
        debugPrint: true,
        documentRootPath: 'docs',
        scanStartPath: 'advanced-usage',
        resolvePath: '/advanced-usage/',
        manualSortFileNameByPriority: ['guide', 'advanced-usage'],
        excludeFiles: ['changelog.md'],
        collapsed: false,
        capitalizeFirst: true,
        useTitleFromFileHeading: true,
        useTitleFromFrontmatter: true,
        frontmatterOrderDefaultValue: 9, // For 'CHANGELOG.md'
        sortMenusByFrontmatterOrder: true
      }
    ]),
```

3. Run the demo website (`npm run docs:dev`)
4. Notice that the links in the sidebar do not work

**Expected behavior** A clear and concise description of what you expected to happen.

I expect the `resolvePath` in the above example to be prepended, so that the sidebar items _do_ work

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Brave

**Additional context** Add any other context about the problem here.

**Comment by DanielTrommel** [comment]
Tried it locally, and it seems that 

```
            if (options.scanStartPath) {
              childItemPathDisplay = childItemPathDisplay.replace(
                new RegExp(`^${options.scanStartPath}`, 'g'),
                ''
              );
            }
```

Needs to become:

```
            if (options.scanStartPath) {
              childItemPathDisplay = childItemPathDisplay.replace(
                new RegExp(`^${options.scanStartPath}`, 'g'),
                options.resolvePath ?? ''
              );
            }
```

**Comment by DanielTrommel** [comment]
Sorry, trying this out a second time, for some reason it seems to work.  I must have mixed up my initial test.

My original problem (with my own vitePress setup) persists.  Will try to create another reproduction.

**Comment by DanielTrommel** [comment]
ok, found out why it did not work on my VitePress setup:  

```
generateSidebar(
      {},
      {}
    )
```

Was missing the [ ] brackets to denote an array.

**Comment by jooy2** [comment]
Hello, thank you for using `vitepress-sidebar`!

I'm glad to hear that your issue has been resolved. Thank you for sharing your use case.

If you have any new issues or comments, please submit a new issue and i'll move this one to Done.

Regards,
