### ISSUE TITLE
Allow control over text of group titles

### ISSUE THREAD

**Issue by jasonkuhrt** [jooy2/vitepress-sidebar#175]
I'd like to be able to capitalize the group titles like we can with menu titles. IIUC this is not possible. Could we allow that?

![CleanShot 2024-09-13 at 14 04 51@2x](https://github.com/user-attachments/assets/da34db9e-16d3-4972-abab-6fb035ef13ac)

**Comment by jasonkuhrt** [comment]
A variation of this issue:

![CleanShot 2024-09-13 at 14 38 52@2x](https://github.com/user-attachments/assets/399ba871-56c6-42db-b9f2-d9b404c5123b)

**Comment by jooy2** [comment]
Hello, Thank you for using `vitepress-sidebar`.

Formatting options for folder (group) names are provided, and you can use several methods to automatically convert folder names.

## Method A: Use `capitalizeFirst`, `capitalizeEachWords` options

This option applies not only to the File menu, but also to the Folder (Group) menu. For example, the examples below are the results of utilizing each option:

### `capitalizeFirst`

- `abc-folder` -> `Abc-folder`
- `abc def folder` -> `Abc def folder`

### `capitalizeEachWords`

This option capitalizes the first letter of each word based on spaces.

- `abc-folder` -> `Abc-folder`
- `abc def folder` -> `Abc Def Folder`

## Method B: Use `useFolderTitleFromIndexFile` and `convertSameNameSubFileToGroupIndexPage` options

These two options are useful for naming folders that are a little more descriptive. One thing to note is that the referenced files can be rendered as documents in VitePress.

The `useFolderTitleFromIndexFile` option uses the Markdown h1 text or the `title` value of the frontmatter from the `index.md` file in that folder. The `index.md` file is also displayed in the menu, depending on the option.

The `convertSameNameSubFileToGroupIndexPage` option will pull the title from the markdown h1 tag or the `title` value of the frontmatter of the file, if there is a file with the same name as the folder, and the folder link will point to that document. And the file will not appear in the menu, and the folder link will point to that document.

---

I hope this resolves your issue. If you have any other questions or issues, please leave an additional reply, and i'll close the issue when i feel the issue has been resolved.

Regards,

**Comment by jasonkuhrt** [comment]
Hey, thanks, yeah that's what I tried but it doesn't seem to be working. Here's a screenshot showing the detail of my context:

![CleanShot 2024-09-16 at 22 06 42@2x](https://github.com/user-attachments/assets/77955c13-8a1f-4dbc-ba25-0d689a1f9bb3)

Am I doing something wrong?

**Comment by jooy2** [comment]
Hello,

The reason `capitalizeEachWords` was not working correctly was because it was previously separating words based on spaces. 

This meant that a title of `getting started` would be correctly converted to `Getting Started`, but a special character delimited file like `10_getting-started` would not produce the expected value.

I fixed this to make it compatible with other special characters as well, and `capitalizeEachWords` now separates words based on alphabets + special characters.

Please upgrade the plugin to version `1.27.0` and check if your requirements are resolved.

Regards,

**Comment by jooy2** [comment]
Hello!

Can you let me know if this issue has been resolved recently? If there is no response, i will consider it resolved and close the issue.
If you continue to experience the issue, please feel free to leave a reply.

Regards,

**Comment by jasonkuhrt** [comment]
Hey @jooy2, I can confirm that it's working now how I expected. Thank you!
