### ISSUE TITLE
Incompatible Node Version Requirement in 1.26.0: Dropped Support for Node 18

### ISSUE THREAD

**Issue by Heggria** [jooy2/vitepress-sidebar#180]
**Describe the bug**

When I upgraded the package dependencies, vitepress-sidebar also updated to version 1.26.0 following the MINOR versioning rule. However, it indicated that the required Node version had changed and no longer supports version 18.

> This error occurred while installing the dependencies of vitepress-sidebar@1.26.0:
> 
> Your Node version is incompatible with "glob@11.0.0".
> Expected version: 20 || >=22
> Got: v18.20.4

I believe this is a MAJOR change. Reference: https://gist.github.com/jonlabelle/706b28d50ba75bf81d40782aa3c84b3e

**Comment by jooy2** [comment]
Hello, thank you for using `vitepress-sidebar` and reporting the bug.

This is an issue with the `glob` package, which was recently introduced and fixed in version `1.26.1`. Could you please upgrade to that version and see if the issue persists?

Regards,
