### ISSUE TITLE
Rename setting `convertSameNameSubFileToGroupIndexPage` to `useFolderLinkFromSameNameSubFile` for consistency

### ISSUE THREAD

**Issue by maxwowpow** [jooy2/vitepress-sidebar#184]
Rename this
`convertSameNameSubFileToGroupIndexPage`

to 

`useFolderLinkFromSameNameSubFile`

to be consistent with

`useFolderLinkFromIndexFile`

PS: just killed another evening debugging why the folder links are clickable.
Cheers.

**Comment by jooy2** [comment]
Hello, thank you for reporting the issue.

This option was suggested before the `useFolderLinkFromIndexFile` option was added. It aims to use a subfile as an index page and at the same time not show that file in the sidebar.

The difference is that the `useFolderLinkFromIndexFile` option does not separately handle not showing the file in the sidebar (which is handled by the `includeFolderIndexFile` option).

However, I now agree with you about changing the name according to your comment for uniformity of both options.

I have changed the name to `useFolderLinkFromSameNameSubFile` as you requested, which is reflected in the `1.28.0` version.

Thank you.
