### ISSUE TITLE
`capitalizeEachWords: true` shouldn't consider numbers as a separator?

### ISSUE THREAD

**Issue by shinebayar-g** [jooy2/vitepress-sidebar#185]
**Describe the bug** When `capitalizeEachWords: true` is set, `cdk8s.md` is becoming a `Cdk8S`

**To Reproduce** Set `capitalizeEachWords: true` and create `cdk8s.md` file or folder

**Expected behavior** It should become `Cdk8s`?

Or is there a way to exclude this specific file from getting capitalized in the sidebar? I'd like to prefer it to stay all lowercase for this one if possible.

**Comment by jooy2** [comment]
Hello, thanks for using `vitepress-sidebar`!

Yes, this is a bug. Thanks for letting me know about the issue and it has been fixed in version `1.28.0`.

Thank you.
