### ISSUE TITLE
[Multi Sidebars] not work in defaultTheme

### ISSUE THREAD

**Issue by just-a-stone** [jooy2/vitepress-sidebar#194]
### Describe the feature

generate sidebar like
```json
"themeConfig": {
    "sidebar": {
      "/quick-start/": {
        "base": "/quick-start/",
        "items": [
          {
            "text": "one",
            "link": "bootstarp"
          },
          {
            "text": "two",
            "link": "bootstarp2"
          }
        ]
      }
    }
  }
```

but, in my version.  use `defaultTheme`, generate items not work.

> https://ecosystem.vuejs.press/zh/themes/default/config.html#sidebar

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/ea55cd31-4cd2-4060-a81d-e39e8953f5a4" />

how can i fix it ?

**Comment by typed-sigterm** [comment]
Note that this lib is for VitePress, not VuePress.

**Comment by just-a-stone** [comment]
> Note that this lib is for VitePress, not VuePress.

thank you! 
i got it.
