### ISSUE TITLE
sort by frontmatter.order

### ISSUE THREAD

**Issue by mcondarelli** [jooy2/vitepress-sidebar#65]
Would be possible to introduce file and directory sort by frontmatter `order:` tag?
That would be more consistent than using `sortByFileName:`.
Files in each directory should be sorted in `order:`  ascending order.
Directories should use the same way using `order:` found in `subdir/index.md` (if any).
I could try to help but I'm not a JavaScript programmer (more python/C/C++/java) and I would need directions to move around.
I am fully available for testing, if useful.

**Comment by jooy2** [comment]
Hello, thanks for using `vitepress-sidebar` and for the feedback.

I'm not sure how difficult this would be, but I'll try to implement it as soon as I have some free time.

Thanks!

**Comment by mcondarelli** [comment]
Thanks @jooy2.
I went ahead and implemented something "working for me".
I can provide git diffs and/or a proper pull request, if preferred, but please review closely as, as said, I'm **not** a JS programmer.

**Comment by jooy2** [comment]
Hello, Thank you for your patience.

I just released version `1.11.0` with some improvements for this issue.

I added the options `sortMenusByName` and `sortMenusOrderByDescending` to allow reordering based on the renamed name, rather than based on the folder tree, after the menu has been renamed with `frontmatter` and markdown heading.

Could you please try setting `sortMenusByName` to `true` after upgrading to this version and see if that resolves the issue?

Regards,

**Comment by Net-Slayer** [comment]
I don't think this solves the issue? 
I believe the request was for an option to sort by a frontmatter "order" value.
![image](https://github.com/jooy2/vitepress-sidebar/assets/14405930/dbdf15ca-9b95-40cc-b53b-8dd7024bca14)
The folder order (collapsible headings), would be sorted by the "order: {value}" ascending, from the frontmatter in _index.md.
The file order (page links), would be sorted within the heading by the same "order: {value}" ascending from the frontmatter in the files.

**Comment by jooy2** [comment]
Hello. Thanks for the detailed explanation.

I have released version `1.12.0` which adds `sortMenusByFrontmatterOrder` option to sort menus based on frontmatter's `order` property.

I would appreciate it if you could confirm if the new version resolves your issue.

**Comment by jooy2** [comment]
If you run into any new issues, please open a new issue. This feature has been implemented, so I'll close the issue.
