### ISSUE TITLE
collapse depth 1

### ISSUE THREAD

**Issue by awbait** [jooy2/vitepress-sidebar#71]
Hi, is it possible to make the collapsed folders displayed when installing collapseDepth:1?

**Comment by jooy2** [comment]
Hello, Thank you for using the `vitepress-sidebar` plugin.

In the current version, `collapseDepth` was also affecting the root content (table of content).

As a result, i've released version `1.9.0` which manages the root content with a separate option called `rootGroupCollapsed` and fixes `collapseDepth` to display correctly.

See: https://github.com/jooy2/vitepress-sidebar/blob/master/CHANGELOG.md

After upgrading to version `1.9.0`, please check if the menu expands on the intended step.

If you also need to display folders where no files exist, please set the `includeEmptyFolder` option to `true`.

Thanks!

**Comment by awbait** [comment]
Thank you! Works great
